# Generated by Django 6.1.1 on 2026-09-23 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descicao',
            new_name='descricao',
        ),
    ]
